// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-muL0TrJop-Mh-LtZLPmVP0RFkWByjbY',
    appId: '1:291771214045:web:e150b6db0efdb658cb9334',
    messagingSenderId: '291771214045',
    projectId: 'notes-2327240094',
    authDomain: 'notes-2327240094.firebaseapp.com',
    storageBucket: 'notes-2327240094.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF6quWjOq2wDKIr6V347qZdz-M5c1TIxU',
    appId: '1:291771214045:android:62ee37d5b102382dcb9334',
    messagingSenderId: '291771214045',
    projectId: 'notes-2327240094',
    storageBucket: 'notes-2327240094.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW1kviONO5L1eBLIYxLPIwxcOPSvNQ3QY',
    appId: '1:291771214045:ios:652f79e4c184a314cb9334',
    messagingSenderId: '291771214045',
    projectId: 'notes-2327240094',
    storageBucket: 'notes-2327240094.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );
}
